export { default as trademark } from '@/api/product/trademark'
export { default as attr } from '@/api/product/attr'
export { default as category } from '@/api/product/category'
export { default as sku } from '@/api/product/sku'
export { default as spu } from '@/api/product/spu'
